/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.methodfinder;

import static org.junit.Assert.assertTrue;

import java.lang.reflect.Method;

import org.junit.Test;

public class ApplicationTest {
    @Test
    public void test() throws NoSuchMethodException, SecurityException {
        final Method method = IEntityService.class.getMethod("methodWithParameter", Object.class);
        final Class<?> targetClass = DemoService.class;

        final Method result = targetClass.getMethod(method.getName(), method.getParameterTypes());

        assertTrue(result.getDeclaringClass().equals(DemoService.class));
    }

}
